include:
 - 'https://source.puri.sm/Librem5/librem5-ci/raw/master/librem5-pipeline-definitions.yml'

stages:
 - build
 - test+docs
 - package
 - deploy

default:
  # Protect CI infra from rogue jobs
  timeout: 15 minutes
  # Allow jobs to be caneled on new commits
  interruptible: true
  # Retry on infra hickups automatically
  retry:
    max: 1
    when:
      - 'api_failure'
      - 'runner_system_failure'
      - 'scheduler_failure'
      - 'stuck_or_timeout_failure'

variables:
  DEPS: git lcov
  ALPINE_EDGE_DEPS: |
        git meson ninja gnome-desktop-dev gobject-introspection-dev
        libinput-dev wayland-dev wayland-protocols libxkbcommon-dev wlroots-dev
        xwayland-dev
  XVFB_RUN: xvfb-run -s -noreset
  DEBIAN_IMAGE: $CI_REGISTRY/world/phosh/phoc/debian:v0.0.20230722

.build: &build
  script:
    - export LC_ALL=C.UTF-8
    - git submodule update --init
    - meson setup _build $BUILD_ARGS
    - meson compile -C _build
    - meson install -C _build

.before_script_debian: &before_script_debian
  - rm -f ../* || true
  - eatmydata apt-get -y update
  - eatmydata apt-get -y install $DEPS xwayland python3-docutils
  - dpkg -l

.before_script_alpine: &before_script_alpine
  - apk -q add alpine-sdk
  - apk -q add $ALPINE_EDGE_DEPS

.before_script_pureos: &before_script_pureos
  - echo "deb http://repo.pureos.net/pureos octarine main" > /etc/apt/sources.list.d/octarine.list
  - apt-get -y update
  - apt-get -y install -t octarine libwlroots-dev

build-with-xwayland-debian-bookworm:
  stage: build
  image: ${DEBIAN_IMAGE}
  before_script: *before_script_debian
  variables:
     BUILD_ARGS: -Dembed-wlroots=disabled -Dxwayland=enabled -Db_coverage=true
  <<: *build
  artifacts:
    paths:
      - _build
  except:
    variables:
      - $PKG_ONLY == "1"

build-with-xwayland-alpinelinux-edge:
  stage: build
  image: alpine:edge
  before_script: *before_script_alpine
  variables:
     BUILD_ARGS: -Dxwayland=enabled
  <<: *build
  allow_failure: true
  except:
    variables:
      - $PKG_ONLY == "1"

build-without-xwayland-alpinelinux-edge:
  stage: build
  image: alpine:edge
  before_script: *before_script_alpine
  variables:
     BUILD_ARGS: -Dembed-wlroots=disabled -Dxwayland=disabled
  <<: *build
  allow_failure: true
  except:
    variables:
      - $PKG_ONLY == "1"


unit-test-with-xwayland-debian-bookworm:
  stage: test+docs
  image: ${DEBIAN_IMAGE}
  needs:
    - build-with-xwayland-debian-bookworm
  before_script: *before_script_debian
  script:
    - WLR_RENDERER=pixman ${XVFB_RUN} meson test --print-errorlogs -C _build
    - ninja -C _build coverage
  coverage: '/^lines:\s+([\d.]+\%)\s+/'
  artifacts:
    when: always
    reports:
      junit:
        - _build/meson-logs/testlog.junit.xml
    paths:
      - _build
  except:
    variables:
      - $PKG_ONLY == "1"

asan-test-native-debian-bookworm:
  stage: test+docs
  image: ${DEBIAN_IMAGE}
  tags: [ asan ]
  needs: []
  before_script: *before_script_debian
  script:
    - meson setup -Db_sanitize=address _build-asan
    - ninja -C _build-asan data/gschemas.compiled
    - WLR_RENDERER=pixman ${XVFB_RUN} meson test --verbose -C _build-asan
  except:
    variables:
      - $PKG_ONLY == "1"
  allow_failure: true

build-gtkdoc:
  stage: test+docs
  image: ${DEBIAN_IMAGE}
  before_script: *before_script_debian
  variables:
    BUILD_ARGS: -Dgtk_doc=true -Dembed-wlroots=disabled
  script:
    - git clean -dfx
    - 'echo "Build opts: ${BUILD_ARGS}"'
    - meson . _build $BUILD_ARGS
    - ninja -C _build
    - test -f _build/doc/phoc-*/index.html
    - mv _build/doc/phoc-*/ _reference/
  artifacts:
    paths:
      - _reference
  except:
    variables:
      - $PKG_ONLY == "1"

package-debian-bookworm:arm64:
  variables:
    L5_DOCKER_IMAGE: debian:bookworm
  tags:
    - aarch64
  extends: .l5-build-debian-package
  before_script:
    - echo "deb http://deb.debian.org/debian/ sid main" > /etc/apt/sources.list.d/sid.list
    - apt-get -y update
    - apt-get -y -t sid build-dep .

package-pureos-byzantium:sanitizers:arm64:
  variables:
    L5_DOCKER_IMAGE: pureos/byzantium
    DEB_BUILD_PROFILES: 'pkg.phoc.embedwlroots pkg.phoc.sanitizers'
  before_script: *before_script_pureos
  tags:
    - aarch64
  when: manual
  extends: .l5-build-debian-package

pages:
  stage: deploy
  needs:
    - build-gtkdoc
  script:
    - mv _reference/ public/
  artifacts:
    paths:
      - public
  only:
    - main
